repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - pre-push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.30.0
- repo: https://github.com/pdm-project/pdm
  rev: 2.19.3
  hooks:
  - id: pdm-lock-check
  - id: pdm-sync
  - id: pdm-export
    args: ['-o', 'requirements.txt', '--without-hashes']
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.385
  hooks:
  - id: pyright
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.1
  hooks:
  - id: ruff
  - id: ruff-format
