"""add brands.

Revision ID: 1728933515
Revises: 1728851480
Create Date: 2024-10-14 15:18:35.429481

"""

# ruff: noqa
# pyright: basic

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1728933515"
down_revision: str | None = "1728851480"
branch_labels: str | Sequence[str] | None = ()
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Marcas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sqlmodel.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Marcas")
    # ### end Alembic commands ###
