"""add Escolaridades table.

Revision ID: 1729091511
Revises: 1729090491
Create Date: 2024-10-16 11:11:51.115650

"""

# ruff: noqa
# pyright: basic

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1729091511"
down_revision: str | None = "1729090491"
branch_labels: str | Sequence[str] | None = ()
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Escolaridades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sqlmodel.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Escolaridades")
    # ### end Alembic commands ###
