"""add Produtos table.

Revision ID: 1729090491
Revises: 1728933515
Create Date: 2024-10-16 10:54:51.243511

"""

# ruff: noqa
# pyright: basic

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1729090491"
down_revision: str | None = "1728933515"
branch_labels: str | Sequence[str] | None = ()
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Produtos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sqlmodel.AutoString(), nullable=False),
        sa.Column("valor_venda", sa.Float(), nullable=False),
        sa.Column("quantidade_em_estoque", sa.Integer(), nullable=False),
        sa.Column("marca_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["marca_id"],
            ["Marcas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Produtos")
    # ### end Alembic commands ###
