"""add instruction level to employees.

Revision ID: 1729092329
Revises: 1729091511
Create Date: 2024-10-16 11:25:29.397263

"""

# ruff: noqa
# pyright: basic

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1729092329"
down_revision: str | None = "1729091511"
branch_labels: str | Sequence[str] | None = ()
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column(
            "Funcionários",
            sa.Column(
                "escolaridade_id",
                sa.Integer(),
                sa.ForeignKey("Escolaridades.id", name="fk_escolaridade_id"),
                nullable=True,
            ),
        )
    except NotImplementedError:
        with op.batch_alter_table("Funcionários") as batch_op:
            batch_op.add_column(
                sa.Column(
                    "escolaridade_id",
                    sa.Integer(),
                    sa.ForeignKey(
                        "Escolaridades.id", name="fk_escolaridade_id"
                    ),
                    nullable=True,
                )
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    """."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_escolaridade_id", "Funcionários", type_="foreignkey"
    )
    op.drop_column("Funcionários", "escolaridade_id")
    # ### end Alembic commands ###
