"""add change prices from float to decimal.

Revision ID: 1730218775
Revises: 1730166417
Create Date: 2024-10-29 12:19:35.903540

"""

# ruff: noqa
# pyright: basic

from collections.abc import Sequence

import sqlalchemy as sa
from src.utils import all_types as at
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1730218775"
down_revision: str | None = "1730166417"
branch_labels: str | Sequence[str] | None = ()
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Contas a receber", schema=None) as batch_op:
        batch_op.alter_column(
            "valor",
            existing_type=sa.FLOAT(),
            type_=sa.Numeric(scale=2),
            existing_nullable=False,
        )

    with op.batch_alter_table("Funcionários", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_Funcionários_email"), ["email"]
        )

    with op.batch_alter_table(
        "Itens da ordem de serviço", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "valor_total_do_item",
            existing_type=sa.FLOAT(),
            type_=sa.Numeric(scale=2),
            existing_nullable=False,
        )

    with op.batch_alter_table("Ordens de serviço", schema=None) as batch_op:
        batch_op.alter_column(
            "valor_total_da_ordem",
            existing_type=sa.FLOAT(),
            type_=sa.Numeric(scale=2),
            existing_nullable=False,
        )

    with op.batch_alter_table("Produtos", schema=None) as batch_op:
        batch_op.alter_column(
            "valor_venda",
            existing_type=sa.FLOAT(),
            type_=sa.Numeric(scale=2),
            existing_nullable=False,
        )
        batch_op.drop_index("ix_Produtos_nome")
        batch_op.create_index(
            batch_op.f("ix_Produtos_nome"), ["nome"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Produtos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_Produtos_nome"))
        batch_op.create_index("ix_Produtos_nome", ["nome"], unique=False)
        batch_op.alter_column(
            "valor_venda",
            existing_type=sa.Numeric(scale=2),
            type_=sa.FLOAT(),
            existing_nullable=False,
        )

    with op.batch_alter_table("Ordens de serviço", schema=None) as batch_op:
        batch_op.alter_column(
            "valor_total_da_ordem",
            existing_type=sa.Numeric(scale=2),
            type_=sa.FLOAT(),
            existing_nullable=False,
        )

    with op.batch_alter_table(
        "Itens da ordem de serviço", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "valor_total_do_item",
            existing_type=sa.Numeric(scale=2),
            type_=sa.FLOAT(),
            existing_nullable=False,
        )

    with op.batch_alter_table("Funcionários", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_Funcionários_email"), type_="unique"
        )

    with op.batch_alter_table("Contas a receber", schema=None) as batch_op:
        batch_op.alter_column(
            "valor",
            existing_type=sa.Numeric(scale=2),
            type_=sa.FLOAT(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
