"""big changes.

Revision ID: 1730140121
Revises: 1729710942
Create Date: 2024-10-28 14:28:41.074550

"""

# ruff: noqa
# pyright: basic

from collections.abc import Sequence

import sqlalchemy as sa
from src.utils import all_types as at
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1730140121"
down_revision: str | None = "1729710942"
branch_labels: str | Sequence[str] | None = ()
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "Cargos dos funcionários", schema=None
    ) as batch_op:
        batch_op.drop_index("ix_Cargos dos funcionários_nome")
        batch_op.create_index(
            batch_op.f("ix_Cargos dos funcionários_nome"),
            ["nome"],
            unique=True,
        )

    with op.batch_alter_table("Clientes", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_Clientes_cpf"), ["cpf"]
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_Clientes_email"), ["email"]
        )

    with op.batch_alter_table("Empresa", schema=None) as batch_op:
        batch_op.drop_index("ix_Empresa_nome")
        batch_op.create_index(
            batch_op.f("ix_Empresa_nome"), ["nome"], unique=True
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_Empresa_cnpj"), ["cnpj"]
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_Empresa_email"), ["email"]
        )

    with op.batch_alter_table("Escolaridades", schema=None) as batch_op:
        batch_op.drop_index("ix_Escolaridades_nome")
        batch_op.create_index(
            batch_op.f("ix_Escolaridades_nome"), ["nome"], unique=True
        )

    with op.batch_alter_table("Fornecedores", schema=None) as batch_op:
        batch_op.drop_index("ix_Fornecedores_nome")
        batch_op.create_index(
            batch_op.f("ix_Fornecedores_nome"), ["nome"], unique=True
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_Fornecedores_cnpj"), ["cnpj"]
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_Fornecedores_email"), ["email"]
        )

    with op.batch_alter_table("Funcionários", schema=None) as batch_op:
        batch_op.alter_column(
            "cargo_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "escolaridade_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_Funcionários_cpf"), ["cpf"]
        )

    with op.batch_alter_table(
        "Itens da ordem de serviço", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "produto_id", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("Marcas", schema=None) as batch_op:
        batch_op.drop_index("ix_Marcas_nome")
        batch_op.create_index(
            batch_op.f("ix_Marcas_nome"), ["nome"], unique=True
        )

    with op.batch_alter_table("Ordens de serviço", schema=None) as batch_op:
        batch_op.alter_column(
            "tecnico_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "cliente_id", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("Produtos", schema=None) as batch_op:
        batch_op.alter_column(
            "marca_id", existing_type=sa.INTEGER(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Produtos", schema=None) as batch_op:
        batch_op.alter_column(
            "marca_id", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("Ordens de serviço", schema=None) as batch_op:
        batch_op.alter_column(
            "cliente_id", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "tecnico_id", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("Marcas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_Marcas_nome"))
        batch_op.create_index("ix_Marcas_nome", ["nome"], unique=False)

    with op.batch_alter_table(
        "Itens da ordem de serviço", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "produto_id", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("Funcionários", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_Funcionários_cpf"), type_="unique"
        )
        batch_op.alter_column(
            "escolaridade_id", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "cargo_id", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("Fornecedores", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_Fornecedores_email"), type_="unique"
        )
        batch_op.drop_constraint(
            batch_op.f("uq_Fornecedores_cnpj"), type_="unique"
        )
        batch_op.drop_index(batch_op.f("ix_Fornecedores_nome"))
        batch_op.create_index("ix_Fornecedores_nome", ["nome"], unique=False)

    with op.batch_alter_table("Escolaridades", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_Escolaridades_nome"))
        batch_op.create_index("ix_Escolaridades_nome", ["nome"], unique=False)

    with op.batch_alter_table("Empresa", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_Empresa_email"), type_="unique"
        )
        batch_op.drop_constraint(batch_op.f("uq_Empresa_cnpj"), type_="unique")
        batch_op.drop_index(batch_op.f("ix_Empresa_nome"))
        batch_op.create_index("ix_Empresa_nome", ["nome"], unique=False)

    with op.batch_alter_table("Clientes", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_Clientes_email"), type_="unique"
        )
        batch_op.drop_constraint(batch_op.f("uq_Clientes_cpf"), type_="unique")

    with op.batch_alter_table(
        "Cargos dos funcionários", schema=None
    ) as batch_op:
        batch_op.drop_index(batch_op.f("ix_Cargos dos funcionários_nome"))
        batch_op.create_index(
            "ix_Cargos dos funcionários_nome", ["nome"], unique=False
        )

    # ### end Alembic commands ###
