"""add service ordem items relationship.

Revision ID: 1730166417
Revises: 1730140121
Create Date: 2024-10-28 21:46:57.269267

"""

# ruff: noqa
# pyright: basic

from collections.abc import Sequence

import sqlalchemy as sa
from src.utils import all_types as at
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1730166417"
down_revision: str | None = "1730140121"
branch_labels: str | Sequence[str] | None = ()
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "Itens da ordem de serviço", schema=None
    ) as batch_op:
        batch_op.add_column(
            sa.Column("ordem_de_servico_id", sa.Integer(), nullable=False)
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_Itens da ordem de serviço_ordem_de_servico_id_Ordens de serviço"
            ),
            "Ordens de serviço",
            ["ordem_de_servico_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "Itens da ordem de serviço", schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_Itens da ordem de serviço_ordem_de_servico_id_Ordens de serviço"
            ),
            type_="foreignkey",
        )
        batch_op.drop_column("ordem_de_servico_id")

    # ### end Alembic commands ###
